### ISSUE TITLE
readme example not working

### ISSUE THREAD

**Issue by fhaselbeck** [vd1371/PyImbalReg#2]
Hi guys,

thanks for your work. I had some issues with using the library and I finally figured out that the example in the readme is wrong.

In the readme `rel_func` is set to `None` with a comment that the default relevance function will be used.
Unfortunately, this is not true. If `None` is set, then no relevance function gets set in the constructor and the code crashes.
`rel_func='default'` would be the right choice just as in the example files.

Would be good to correct this, so other people do not get strange problems when trying to use the lib.

Kind regards,
Florian

**Comment by vd1371** [comment]
Hi Florian,

Thanks for raising this issue. The default value of rel_fun is None:

    rel_func = params.pop("rel_func", None)

The issue was with the DataHandler and now is fixed:

    # The default behaviour
    if rel_func == 'default' or rel_func is None:
        average, std = DataHandler.Y.mean(), DataHandler.Y.std()

**Comment by vd1371** [comment]
Hi Florian,

Thanks for raising this issue. The default value of rel_func is None:
```python
rel_func = params.pop("rel_func", None)
```

The issue was with the DataHandler and now is fixed:

```python
# The default behaviour
if rel_func == 'default' or rel_func is None:
    average, std = DataHandler.Y.mean(), DataHandler.Y.std()
```

**Comment by vd1371** [comment]
Rectifies with many thanks.
Please refer to fe455c619e0db44bc017cf0112c6ee514f566908
