### ISSUE TITLE
Big issue when creating second sampling object 

### ISSUE THREAD

**Issue by fhaselbeck** [vd1371/PyImbalReg#3]
Hi guys,

I detected a big issue if one wants to create a second, also if it is another one, object for sampling. The reason is that in the parent class DataHandler you are setting the parent class attributes instead of the ones of the object. This may cause lot of problems, for example one is not able to change parameters in a running program or instantiate a second sampler. I fixed the code. The if-clause aksing for the instantiation of the object is also not needed. 

Furthermore, I fixed a second issue. The attribute for the random_state is never set if it was no one was provided, so it is never set to None and therefore the program crashes in these cases.

Moreover, there would be potential in making the code shorter and easier, e.g. by directly setting the class attributes. But I did not change this, as I did not want to change your coding style. 

I encountered a problem after my fix with `Example-GNHF.py `. I had to set `bins=25` to prevent a crash.

Unfortunately I was not allowed to create a pull request, so find the code for the fix of  `DataHandler.py` below. It would be great if you could copy it and fix the issue. 

```
# Loading dependencies
import numpy as np
import pandas as pd
import warnings
from scipy.stats import norm

class DataHandler:

	instance = None

	def __init__(self, **params):
		'''Building the base for other methods built upon is

		This object is developed for handling the data before conduting any analysis on it
		These processes include but not limited to checking the Nan files, data type, etc.

		df: The data as a pandas dataframe
		y_col: The name of the Y column header
		rel_func: The relevance function
		threshold: Thereshold to dertermine the normal and rare samples
		should_log_transform: Useful when there is a huge difference betweem
				the order of the target values
		'''
		df = params.pop("df", None)
		y_col = params.pop("y_col", None)
		rel_func = params.pop("rel_func", None)
		threshold = params.pop("threshold", 0.9)
		o_percentage = params.pop("o_percentage", 2)
		u_percentage = params.pop("u_percentage", 0.2)
		perm_amp = params.pop("perm_amp", 0.1)
		categorical_columns = params.pop("categorical_columns", None)
		bins = params.pop("bins", 10)
		should_log_transform = params.pop("should_log_transform", False)
		random_state = params.pop("random_state", None)

		self.random_state = random_state
		np.random.seed(random_state)

		# The current version of PyImbalReg is designed to work only with pandas dataframes
		if not isinstance(df, pd.DataFrame):
			raise TypeError ("The current version of PyImbalReg can "\
								"only work on pandas dataframes.")

		# The data must not contain any Nan values
		if df.isnull().values.any():
			raise ValueError ("The dataframe consists NaN values. "\
									"Please consider removing them.")

		# Getting the Y column
		if y_col is None:
			y_col = df.columns.values[-1]

		# y should be either None or string
		elif not isinstance(y_col, str):
			raise TypeError ("y must be either None or a string")

		# if y is not one of the data columns
		elif not y_col in df.columns.values:
			raise ValueError ("y must be a column name, but it's not")

		# Rearrangin the dataframe so the last column be Y
		if df.columns.values[-1] != y_col:
			cols = df.columns.tolist()
			idx = cols.index(y_col)
			cols = cols[:idx] + cols[idx+1:] + [cols[idx]]
			df = df[cols]

		self.Y = np.log10(df.iloc[:, -1]) if should_log_transform else df.iloc[:, -1]

		self.df = df
		self.y_col = y_col

		'''
		Set the relevance function and threshold
		Relevenace function is a relevance/utility function that maps the Y to [0, 1]
		Values of u(Y) > threshold are considered as rare samples

		Ref:
		Branco, P., Torgo, L. and Ribeiro, R.P., 2019.
		Pre-processing approaches for imbalanced distributions in regression.
		Neurocomputing, 343, pp.76-99.
		'''

		self.o_percentage = self._is_o_percentage_correct(o_percentage)
		self.u_percentage = self._is_u_percentage_correct(u_percentage)
		self.perm_amp = self._is_perm_amp_correct(perm_amp)
		self.bins = self._is_bins_correct(bins)

		# Finding the categorical columns
		if categorical_columns is None:
			categorical_columns = self.get_categorical_cols(df)
		self.categorical_columns = categorical_columns

		# Setting the relveance function, normal bins, rare bins, ...
		if not rel_func is None:
			self.set_relevance_function(rel_func, threshold)

	# Set the undersampling percentage
	def set_u_percentage(self, u_percentage):
		self.u_percentage = self._is_u_percentage_correct(u_percentage)

	# Set the oversampling percentage
	def set_o_percentage(self, o_percentage):
		self.o_percentage = self._is_o_percentage_correct(o_percentage)

	# Assigning the relevance function and the threshold
	def set_relevance_function(self, rel_func, threshold):

		# The default behaviour
		if rel_func == 'default':
			average, std = self.Y.mean(), self.Y.std()

			# Default relevance function is based on probability distribution function ...
			# ... of normal distribution
			def default_rel_func(x, average = average, std = std, norm_dist = norm):
				return 1 - norm_dist.pdf(x, loc = average, scale = std) / \
							 norm_dist.pdf(average, loc = average, scale = std)

			self.rel_func = default_rel_func

		# Check if the rel_fun is a function
		elif not callable(rel_func):
			raise TypeError ("The rel_func is expected to be a fuction, but it's not")

		# Set the relevance function
		else:
			self.rel_func = rel_func

		# Finding the relevance value of the Y
		self.Y_utility = self.Y.apply(self.rel_func)

		if any(self.Y_utility > 1) or any(self.Y_utility < 0):
			raise ValueError ("It is expected that the relevance function returns\
								values between [0, 1]. But it doesn't. Please re-define your function")

		# Check if the threshold is a float
		if not isinstance(threshold, (float)):
			raise ValueError ("The threshold must be float")
		# Check if the threshold is between 0 and 1
		elif not (threshold > 0 and threshold < 1):
			raise ValueError ("The threshold must be between [0,1]. But it's not.")

		self.threshold = threshold

		# Finding the rare and normal values
		self.find_normal_rare_values()

	# Finding the relevance value of the Y
	def find_normal_rare_values(self, should_sort = True):

		# Finding bins with the normal Y and rare Y
		self.rare_bins, self.normal_bins = [], []

		if should_sort:
			# Sorting the values of df
			self.df.sort_values(self.df.columns[-1], inplace = True)

		RARE = True

		previous_status = self.rel_func(self.df.iloc[0, -1]) >= self.threshold
		start_idx, last_idx = 0, 0
		for i, idx in enumerate(self.df.index[1:]):

			# Check if it's a rare case or not
			current_status = self.rel_func(self.df.iloc[i, -1]) >= self.threshold

			if not current_status == previous_status or idx == self.df.index[-1]:
				temp_bin = self.df.iloc[start_idx:last_idx, :]
				if previous_status == RARE:
					self.rare_bins.append(temp_bin)
				else:
					self.normal_bins.append(temp_bin)

				start_idx = i

			last_idx = i
			previous_status = current_status

	# Checcikng if the o_percentage is correct
	@staticmethod
	def _is_o_percentage_correct(o_percentage):
		# o_percentage : Oversampling percentage

		# Check if the o_percentage is a float
		if not isinstance(o_percentage, (int, float)):
			raise ValueError ("The o_percentage must be float")
		# Check if the o_percentage is between 0 and 1
		elif not (o_percentage > 1):
			raise ValueError ("The o_percentage must be bigger than 1. But it's not.")

		return o_percentage

	# Checcikng if the u_percentage is correct
	@staticmethod
	def _is_u_percentage_correct(u_percentage):
		# u_percentage : Oversampling percentage

		# Check if the u_percentage is a float
		if not isinstance(u_percentage, (float)):
			raise ValueError ("The u_percentage must be float")
		# Check if the u_percentage is between 0 and 1
		elif not (u_percentage > 0 and u_percentage < 1):
			raise ValueError ("The u_percentage must be between [0,1]. But it's not.")

		return u_percentage

	# Checking if the permutation amplitude is a float
	@staticmethod
	def _is_perm_amp_correct(perm_amp):
		# perm_amp: permutation amplitude
		if not isinstance(perm_amp, (int, float)):
			raise ValueError ("The perm_amp must be float")

		return perm_amp

	# Checking if the bins is an integer
	@staticmethod
	def _is_bins_correct(bins):
		# bins: number of bins for making histogram
		if not isinstance(bins, int):
			raise ValueError ("The bins must be integer")

		return bins

	# Getting the categorical columns of a dataframe
	@staticmethod
	def get_categorical_cols(df):
		# This method is called when the categorical columns are not passed by the user

		warning_message = "\n\n---------------------------------------\n" +\
						"The categorical_columns is not define by you.\n" +\
						"I will try to find the categorical columns using heuristic methods.\n" +\
						"There is a small chance it fails. Consider passing the categorical_columns. \n" +\
						"---------------------------------------\n"
		warnings.warn(warning_message, UserWarning , stacklevel = 2)

		nominal_dtypes = ['object', 'bool', 'datetime64']

		categorical_columns = []
		for col in df.columns:

			# Adding the string, boolean, and datetimes columns
			if df[col].dtypes in nominal_dtypes:
				categorical_columns.append(col)

			# Checking the integer columns
			elif pd.api.types.is_integer_dtype(df[col].dtypes):
				# A heuristic method to check if the column in categorical
				if df[col].nunique() / df[col].count() < 0.05:
					categorical_columns.append(col)

		return categorical_columns

```

**Comment by vd1371** [comment]
Hi, thanks for raising this issue.
I will check it out soon and update it accordingly.

**Comment by fhaselbeck** [comment]
Hi Vahid,

thanks, great. I am happy to contribute to your project ☺
If you open your repo for pull requests, I could also create one so it is less work for you.

Kind regards,
Florian

Florian Haselbeck
University of Applied Sciences Weihenstephan-Triesdorf
TUM Campus Straubing for Biotechnology and Sustainability
PhD Student / Research Assistant Professorship Bioinformatics

Petersgasse 18 | 94315 Straubing | Germany
Phone: +49 9421 187 234
E-Mail: ***@***.******@***.***>
Web:  www.bit.cs.tum.de<http://www.bit.cs.tum.de/>

Von: Vahid Asghari ***@***.***>
Gesendet: Freitag, 19. März 2021 05:16
An: vd1371/PyImbalReg ***@***.***>
Cc: Florian Haselbeck ***@***.***>; Author ***@***.***>
Betreff: Re: [vd1371/PyImbalReg] Big issue when creating second sampling object (#3)


Hi, thanks for raising this issue.
I will check it out soon and update it accordingly.

**Comment by fhaselbeck** [comment]
Hi Vahid,

thanks, I am happy to contribute to your project.

If you enable pull requests, I could also create one so it is less work for you. 

I encountered a second issue caused by the fix above. In the `get()` method of `GaussianNoise()` a new object of `RandomUndersampling()` is created, but as the parameters are no longer stored in the parent class, one needs to pass the parameters to the constructor. Can be fixed by passing the parameters of the existing `GaussianNoise()` object, but maybe you could double check so we do not get any side effects:

`ru = RandomUndersampling(**self.__dict__)` instead of `ru = RandomUndersampling()` in `get()` of `GaussianNoise()`

**Comment by vd1371** [comment]
Hi again,

Thanks for raising these issues.

1- Instantiating the data handler was designed to be this way. There were two reasons behind this choice. First, when the data handler is instantiated, the relevance function and threshold are set. Then, rare/normal bins are separated. This process for big datasets was time-consuming. So, the idea was to find the rare and normal bins only ONCE.

I agree that this design could have been problematic if one wants to instantiate the DataHandler 2 times.

The method for finding rare/normal bins in this commit is replaced with a faster one (about 3 orders of magnitudes faster). So, the separation of rare/normal bins will not be time-consuming anymore.

The DataHanlder is now updated based on your suggestion. Please refer to fe455c619e0db44bc017cf0112c6ee514f566908

For the second reason, please refer to item 4.

2- The second issue about random_state is now fixed as you suggested.

3- Regarding the number of bins in GNHF:
if one sets the number of bins so large that only no sample or only one sample could be found in that bin, undersampling or oversampling of that bin will be meaningless. This is was designed by purpose. Nevertheless, I'm open to any suggestion for dealing with this situation.

4- The previous design didn't let any other instances of DataHandler be created. So, the ```GaussianNoise()``` and the ```RandomUnderSampling()``` would have used the same ```DataHandler```.

With the newer design, your suggestion would perfectly work. Your suggestion is now added. Please refer to fe455c619e0db44bc017cf0112c6ee514f566908

5- Regarding the pull request issue, please read this one and see if it helps:
https://stackoverflow.com/questions/49512707/cant-make-a-pull-request-on-github

If not, please let me know so I can fix it.

Please check the latest commit and see if it works fine. If so, please let me know so I update the package as well.

Bests,

**Comment by fhaselbeck** [comment]
Hi Vahid,

thanks a lot for the update.

As I encountered some differences in comparison to previous results, I had a closer look at `find_normal_rare_values()`. In the old implementation, the last index of each identified bin was not included as slicing for DataFrames is exclusive for the ending index (sum of all index lengths was also less than length of the whole df). 
In the current implementation, it seems right. Just in case anybody else experiences similar issues. 

Kind regards,
Florian

**Comment by vd1371** [comment]
Hi Florian,

Thanks for letting me know.

I'm closing this issue as it seems there is no more problem

Bests,
