### ISSUE TITLE
__init__()

### ISSUE THREAD

**Issue by luna57-lr** [vd1371/PyImbalReg#4]
i run your example, but got this error:

    ro = pir.RandomOversampling(data,              # Passing the data
TypeError: __init__() takes 1 positional argument but 2 were given

**Comment by vd1371** [comment]
Hi,

I apologize for replying late.

Can you please send me the full code so I can help you more?

Also, have you tried passing the data as keyword arguments instead of positional arguments?

Like:
ro = pir.RandomOversampling(**df =** data,...

**Comment by vd1371** [comment]
Seems to be solved

**Comment by luna57-lr** [comment]
Thank you!
